# Variant van app.conf voor gebruik binnen de Docker-container, waar de
# bestanden in /usr/share/nginx/html staan in plaats van /var/www/...

server {
    listen 80;
    listen [::]:80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /data/ {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location ~* \.(css|js)$ {
        add_header Cache-Control "public, max-age=3600";
    }

    gzip on;
    gzip_types text/css application/javascript application/json text/plain;
}
